### ISSUE TITLE
Use GLib.Action

### ISSUE THREAD

**Issue by danrabbit** [lainsce/dot-matrix#3]
https://github.com/lainsce/dot-matrix/blob/8673301922fe429bd432bd91f19460ce761321fb/src/MainWindow.vala#L32

Instead of manually listening for key press events, you should use GLib.Action and add shortcut accelerators that way

**Comment by lainsce** [comment]
I'll research how to do that.

**Comment by lainsce** [comment]
After seeing how it's done, I prefer manually listening since I can be sure that the command fired successfully. GLib.Action also can get weird with split keybind commands in two classes.
