### ISSUE TITLE
Format SVG output with indention

### ISSUE THREAD

**Issue by vanillajonathan** [lainsce/dot-matrix#32]
Format the SVG output with 2 spaces.

Such as:
```xml
<svg...>
  <g...>
    <path...>
  </g>
</svg>
```

**Comment by lainsce** [comment]
I can't control indentation as it's Cairo who's exporting the svg for me.

**Comment by vanillajonathan** [comment]
Oh, it seems unfortunately Cairo has no such feature.
https://valadoc.org/cairo/Cairo.SvgSurface.html
