### ISSUE TITLE
[Feature Request] Set drawing area size with a preferences dialog

### ISSUE THREAD

**Issue by vanillajonathan** [lainsce/dot-matrix#34]
Dot Matrix uses the units `pt` (points) and it also have a big viewbox dimensions.

To make [Bootstrap Icons](https://icons.getbootstrap.com/), I need no units and the viewport 16x16.

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
  <path d="..." />
</svg>
```

**Comment by lainsce** [comment]
Dot Matrix is only for doing a general idea of the glyph you want to make; to edit it later with a more detailed tool like Inkscape like changing the viewport and units.

**Comment by vanillajonathan** [comment]
Does Cairo support drawing without units?
https://valadoc.org/cairo/Cairo.SvgSurface.set_document_unit.html

Maybe there could be an option to define the size of the `Gtk.DrawingArea` and have it centered, so the user can set it to 16x16 then resize the application and the drawing area gets centered and you can only draw in the center?

Inkscape is powerful, but it can be difficult to use.

**Comment by lainsce** [comment]
As you can see in that link, I could specify any unit, but not "no unit", sadly.

I can define the size of the drawing area and center it, but then it loses the simplicity of the app which is just to make something quick without having to think about details.

**Comment by vanillajonathan** [comment]
I like that the app is simple.

An option for defining the drawing area could be hidden under under the triple-dot menu.

**Comment by lainsce** [comment]
OK, I'll work on that then :)

**Comment by lainsce** [comment]
The way this will work, unfortunately, is to make the canvas size 4× the size of your icon, so 16px becomes 64px, and then work on that. However, it does work.

**Comment by vanillajonathan** [comment]
There seems to be a couple of bugs:
- Changing dimensions in the preference dialog sometimes doesn't take effect.
- When closing and opening the preferences dialog, sometimes it has the old values.
- Sometimes I need to restart the application for the preferences to take effect.
- Sometimes changing both the width and he height only triggers change one one of the values.
- Setting the dimensions to 16x16 makes results in just 1 point and makes it impossible to draw anything. When setting it to 16x16 it needs to create 16 horizontal points, and 16 vertical points, and zoom in.

It would be good with a reset button that resets it back to default settings (320x320).

**Comment by lainsce** [comment]
> Changing dimensions in the preference dialog sometimes doesn't take effect.

Due to a GTK4 limitation, you need to press enter for the new value to be set.

> When closing and opening the preferences dialog, sometimes it has the old values.

I think this is related to the above.

> Sometimes I need to restart the application for the preferences to take effect.

I think this is also related to the above.

> Sometimes changing both the width and he height only triggers change one one of the values.

I think this is again, also related to the above. :P

> Setting the dimensions to 16x16 makes results in just 1 point and makes it impossible to draw anything. When setting it to 16x16 it needs to create 16 horizontal points, and 16 vertical points, and zoom in.

I made Dot Matrix to not be an advanced editor that does things like zoom in and fine detail work, etc, it's not meant for that. It's meant to just do something simple that you then transfer to Inkscape or other svg editors for fine-tuning.

**Comment by lainsce** [comment]
Although, a reset button is a nice idea.

**Comment by vanillajonathan** [comment]
Ah, I see, you need to press the enter key in each one of the input fields.
Also the <kbd>Tab</kbd> button doesn't seem to be very useful.

Maybe a workaround could be to trigger a save on the [`changed`](https://docs.gtk.org/gtk4/signal.Editable.changed.html) or [`insert-text`](https://docs.gtk.org/gtk4/signal.Editable.insert-text.html) signal, or implement a save button?

Without having 16x16 represented with 256 (16 vertical, 16 horizontal) dots on the grid, it is not useful for creating 16x16 icons. 😥️

**Comment by lainsce** [comment]
> Ah, I see, you need to press the enter key in each one of the input fields. Also the Tab button doesn't seem to be very useful.
> 
> Maybe a workaround could be to trigger a save on the [`changed`](https://docs.gtk.org/gtk4/signal.Editable.changed.html) or [`insert-text`](https://docs.gtk.org/gtk4/signal.Editable.insert-text.html) signal, or implement a save button?
> 
> Without having 16x16 represented with 256 (16 vertical, 16 horizontal) dots on the grid, it is not useful for creating 16x16 icons. disappointed_relieved

I'll use the `changed` signal when I come back from break.

As for the 16×16, you have to think about the canvas as being dependent of how many dots are there, so to achieve the 256 dots grid, the width and height in the Preferences have to be 300.
