### ISSUE TITLE
Add .linked class to buttons

### ISSUE THREAD

**Issue by vanillajonathan** [lainsce/dot-matrix#35]
Consider adding the GTK CSS class `linked` to the Line, Arc and Inverted Arc buttons.

These three buttons are related and belong to a button group that is separate from the Close All Paths button.

**Comment by lainsce** [comment]
.linked is deprecated in libadwaita; what you want is to a separator with .spacer to be added in-between the "groups" of actions.

**Comment by vanillajonathan** [comment]
I see, thanks for the clarification. Do you like the idea? Are you implementing it?

**Comment by lainsce** [comment]
I do like it, and will implement it in a new release; I am just busy with rewriting Khronos this week.

**Comment by vanillajonathan** [comment]
Now while this add a separation between the "Close All Paths" button and the button group, I don't think this removes the spacing between the three buttons in the button group.

> Toggle buttons can also be linked, to create a control for selecting one of a series of options. This approach is appropriate when the available options are not binary in nature and the options available can be expressed with short labels.

https://developer.gnome.org/hig/patterns/controls/buttons.html

**Comment by lainsce** [comment]
The HIG wasn't updated to correlate with libadwaita new things, so it's a mismatch :P

It's supposed to be like this for any app using libadwaita; it's cohesion with the other ones (example, Obfuscate)
