### ISSUE TITLE
[Feature Request] Add redo functionality

### ISSUE THREAD

**Issue by vanillajonathan** [lainsce/dot-matrix#37]
There is a undo functionality (<kbd>Ctrl</kbd>+<kbd>Z</kbd>) which could have a redo functionality (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd>).

**Comment by lainsce** [comment]
I dunno if I can write a redo, since Undo right now is destructive because it goes back one step of what the user did and disposes of the undone action.

**Comment by lainsce** [comment]
This is in progress.

**Comment by lainsce** [comment]
All done!

**Comment by vanillajonathan** [comment]
There is a minor bug; if you have undo/redo states and click the "New Glyph" button then the redo button will still be enabled.

**Comment by lainsce** [comment]
Oh, oof, forgot about that part. I was so focused on the undo/redo methods that I completely missed this. Thanks for pointing it out :)
