### ISSUE TITLE
Error building: syntax error, expected identifier

### ISSUE THREAD

**Issue by Crilum** [lainsce/dot-matrix#57]
I tried building dot-matrix, but when I ran `sudo ninja install`, it gave me this error:

```
$ sudo ninja install
[14/21] Compiling Vala source ../src/A...gets/Prefs.vala ../src/Widgets/UI.vala
FAILED: io.github.lainsce.DotMatrix.p/src/Application.c io.github.lainsce.DotMatrix.p/src/MainWindow.c io.github.lainsce.DotMatrix.p/src/Services/SettingsManager.c io.github.lainsce.DotMatrix.p/src/Widgets/Prefs.c io.github.lainsce.DotMatrix.p/src/Widgets/UI.c 
valac -C --debug --debug --target-glib=2.68 --pkg libadwaita-1 --pkg gee-0.8 --pkg gtk4 --color=always --directory io.github.lainsce.DotMatrix.p --basedir ../ --gresources=../data/io.github.lainsce.DotMatrix.gresource.xml /home/pi/src/dot-matrix/src/Config.vapi ../src/Application.vala ../src/MainWindow.vala ../src/Services/SettingsManager.vala ../src/Widgets/Prefs.vala ../src/Widgets/UI.vala
../src/Application.vala:45.23-45.23: error: syntax error, expected identifier
        active_window?.present ();
                      ^
Compilation failed: 1 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.

```

**Comment by lainsce** [comment]
Recommended to build it with GNOME Builder and Flatpak.

**Comment by Crilum** [comment]
Thanks for the quick reply, it would be amazing if you could write some instructions for using GNOME Builder in the README.


I'm using arm (a Raspberry Pi 4), so I can't just use the Flatpak. I wish I could.. :)

**Comment by Crilum** [comment]
When I do that, it says:
```
The build target failed to build: Cannot execute pipeline, it has not yet been prepared
```

Which arm version are you using in your Flatpaks? I am on armv7l to be exact, but I can also use arm64 (sometimes called aarch64).

**Comment by Crilum** [comment]
I'm also getting the same error, in the Terminal output of Builder:
```
Application.vala:45.23-45.23: error: syntax error, expected identifier
```

**Comment by lainsce** [comment]
Oh yeah, before you do the run button, if this is the first time opening the project in Builder, update build dependencies by clicking on the entry that says the program's name just to the right of the run button, then click the starry arrow up icon in the popover that opens.

**Comment by Crilum** [comment]
@lainsce Sorry I haven't replied, I haven't been very active. I'll try that once I have some time! Thank you.

**Comment by lainsce** [comment]
Alrighty :)

**Comment by Crilum** [comment]
So, I tried installing Dot Matrix with Flatpak on an arm64 OS, and it worked just fine! :tada: Is it possible to add armv7l (or armhf, if that's what Flatpak wants - they're the same), the 32 bit arm arch to your Flatpak build?

**Comment by lainsce** [comment]
Sadly I don't know how to enable more archiotectures in the build stage for Flatpak. :(

Also, Pi-Apps looks inviting, but I distribute via FlatHub due to ease of maintainability as I'm a single dev and I'd have to maintain in yet another place.

**Comment by Crilum** [comment]
>Sadly I don't know how to enable more archiotectures in the build stage for Flatpak. :(

Oh, ok. :+1: 

>Also, Pi-Apps looks inviting, but I distribute via FlatHub due to ease of maintainability as I'm a single dev and I'd have to maintain in yet another place.

Let me clarify a little bit: Pi-Apps would use Flatpak to install Dot Matrix. You wouldn't have to do anything else, I would just submit (to Pi-Apps) a bash script that installs Dot Matrix with Flatpak, and if it gets added, users would just click install on Pi-Apps, and the script would just run a Flatpak install. 

The description would link to this repo, and you would be listed (along with all the other contributors) as the author of the program.

**Comment by Crilum** [comment]
I'll check out your other apps! :smile: 

I have an [app request](https://github.com/Botspot/pi-apps/issues/1589) for Dot Matrix open on the Pi-Apps repo, so you can check that out if you want.

**Comment by Crilum** [comment]
So it looks like the build arches are specified here: https://flathub.org/builds/#/builders/32/builds/69504 under the `Build Properties` tab

I don't know if you have access to those parameters, but if you could somehow add 32-bit arm to that, Flatpak could have 32-bit builds!

**Comment by Crilum** [comment]
So, I just saw this on Flatpak's [setup guide](https://flatpak.org/setup/Raspberry%20Pi%20OS) for Raspberry Pi OS:
>Important note: As of March 2021, Raspberry Pi computers still ship with the 32-bit version of Raspberry Pi OS. However Flathub started phasing out support for that architecture. If you consider Flathub as an important source of applications, it is recommended to use Raspberry Pi OS 64-bit as newer applications are more likely to be available for that platform.

**Comment by lainsce** [comment]
Yeah, also, I learnt that supporting arm(arm 32-bit) for GTK4 flatpaks is a no-go. Sorry. :(

**Comment by Crilum** [comment]
Well, thanks for all your help!
