### ISSUE TITLE
Some UI errors

### ISSUE THREAD

**Issue by Maccer1** [lainsce/dot-matrix#8]
1- When I open the app it uses all the available screen height but it's not maximized, [it looks like this](https://user-images.githubusercontent.com/8525464/54084914-bc203380-4337-11e9-9196-3938e14d914d.png)
. The maximize button doesn't work either so I can't maximize it.

2 - The button to change the line thickness just goes up (5,6,7....) but never goes down.  I know I can use the shortcuts but still.

3 - Erratic behaviour. Sometimes I don't get a saving prompt when closing the app. Also when I open the app and click two points and then press enter it shows a saving prompt. It somehow executes a close command??? If I click "draw line" then the problem doesn't appear again.

App version is 1.1.0 and I'm using elementaryOS Juno.

The app is really great btw, it may have some mistakes but it looks simple, easy and it's so original. I don't know of anything similar.

**Comment by lainsce** [comment]
>1- When I open the app it uses all the available screen height but it's not maximized, it looks like this. The maximize button doesn't work either so I can't maximize it.

I'll reduce the starting size of the application 25% on both height & width so it can be used properly then :smile: 

2 - The button to change the line thickness just goes up (5,6,7....) but never goes down. I know I can use the shortcuts but still.

I'm working on making the label editable when pressed for quick changing.

3 - Erratic behaviour. Sometimes I don't get a saving prompt when closing the app. Also when I open the app and click two points and then press enter it shows a saving prompt. It somehow executes a close command??? If I click "draw line" then the problem doesn't appear again.

Now that's strange. Possibly just a fluke.

**Comment by lainsce** [comment]
Fixed 1 and 2, 3 is indeed just a phantom bug.
